version: '3.8'

services:
  worker-planillas:
    build: .
    container_name: worker-planillas
    restart: always
    env_file:
      - .env
    networks:
      - planillas-network
    ports:
      - "${WORKER_PORT:-8001}:${WORKER_PORT:-8001}"

networks:
  planillas-network:
    name: planillas-network
    driver: bridge
